# Generated by Django 6.0.5 on 2026-05-18 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa roli')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('color', models.CharField(default='gray', help_text='Dostępne: gray, blue, green, yellow, red, purple, orange', max_length=20, verbose_name='Kolor odznaki')),
                ('can_view_employees', models.BooleanField(default=False, verbose_name='Podgląd pracowników')),
                ('can_edit_employees', models.BooleanField(default=False, verbose_name='Edycja pracowników')),
                ('can_manage_questionnaires', models.BooleanField(default=False, verbose_name='Zarządzanie kwestionariuszami')),
                ('can_manage_tests', models.BooleanField(default=False, verbose_name='Zarządzanie testami')),
                ('can_approve_vacations', models.BooleanField(default=False, verbose_name='Zatwierdzanie wniosków')),
                ('can_manage_balances', models.BooleanField(default=False, verbose_name='Edycja sald urlopowych')),
                ('can_cancel_approved_vacations', models.BooleanField(default=False, verbose_name='Anulowanie zatwierdzonych urlopów')),
                ('can_manage_structure', models.BooleanField(default=False, verbose_name='Zarządzanie strukturą')),
                ('can_view_all_requests', models.BooleanField(default=False, verbose_name='Podgląd wszystkich wniosków')),
            ],
            options={
                'verbose_name': 'Niestandardowa rola',
                'verbose_name_plural': 'Niestandardowe role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nazwa stanowiska')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywne')),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='Umowa do'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='Umowa od'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('uop_nieokreslony', 'UoP — czas nieokreślony'), ('uop_okreslony', 'UoP — czas określony'), ('zlecenie', 'Umowa zlecenie'), ('dzielo', 'Umowa o dzieło'), ('b2b', 'B2B'), ('staz', 'Staż / Praktyka')], max_length=30, verbose_name='Typ umowy'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_exam_next_date',
            field=models.DateField(blank=True, null=True, verbose_name='Następne badanie'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_exam_type',
            field=models.CharField(blank=True, choices=[('wstepne', 'Wstępne'), ('okresowe', 'Okresowe'), ('kontrolne', 'Kontrolne')], max_length=20, verbose_name='Typ badania'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customrole', verbose_name='Niestandardowa rola'),
        ),
    ]
