# Generated by Django 6.0.5 on 2026-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bhp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zwolnienia'),
        ),
    ]
