# Generated by Django 6.0.5 on 2026-06-25 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Firma')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Region')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiony',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customrole',
            name='can_manage_contracts',
            field=models.BooleanField(default=False, verbose_name='Zarządzanie umowami'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='can_post_news',
            field=models.BooleanField(default=False, verbose_name='Publikowanie aktualności'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='can_upload_documents',
            field=models.BooleanField(default=False, verbose_name='Przesyłanie dokumentów'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='can_view_documents',
            field=models.BooleanField(default=False, verbose_name='Podgląd dokumentów'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.company', verbose_name='Firma'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('uop_nieokreslony', 'UoP — czas nieokreślony'), ('uop_okreslony', 'UoP — czas określony'), ('zlecenie', 'Umowa zlecenie'), ('dzielo', 'Umowa o dzieło'), ('b2b', 'B2B'), ('staz', 'Staż / Praktyka')], max_length=30, verbose_name='Typ umowy')),
                ('start_date', models.DateField(verbose_name='Data od')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data do')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Stanowisko')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Umowa',
                'verbose_name_plural': 'Umowy',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.region', verbose_name='Region'),
        ),
    ]
