# Generated by Django 6.0.5 on 2026-06-26 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_company_region_contract_extended_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_managers',
            field=models.ManyToManyField(blank=True, related_name='extra_subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Dodatkowi przełożeni'),
        ),
    ]
