PRACOWNIK_FIELDS = [
    {"key": "imie_nazwisko", "label": "Imię (imiona) i nazwisko", "type": "text", "required": True},
    {"key": "pesel", "label": "Numer ewidencyjny PESEL", "type": "text", "required": True},
    {"key": "miejsce_data_urodzenia_4", "label": "Miejsce i data urodzenia", "type": "text", "required": True},
    {"key": "obywatelstwo", "label": "Obywatelstwo", "type": "text", "required": True},
    {"key": "telefon", "label": "Numer telefonu wraz z numerem kierunkowym", "type": "text", "required": True},
    {"key": "address_section", "label": "Adres zamieszkania w Polsce", "type": "section"},
    {"key": "wojewodztwo", "label": "Województwo", "type": "text", "required": False},
    {"key": "powiat", "label": "Powiat", "type": "text", "required": False},
    {"key": "gmina", "label": "Gmina", "type": "text", "required": False},
    {"key": "poczta", "label": "Poczta", "type": "text", "required": False},
    {"key": "ulica", "label": "Ulica nr domu/nr lokalu", "type": "text", "required": False},
    {"key": "kod_pocztowy", "label": "Kod pocztowy", "type": "text", "required": False},
    {"key": "miejscowosc", "label": "Miejscowość", "type": "text", "required": False},
    {"key": "urzad_skarbowy", "label": "Nazwa Urzędu Skarbowego", "type": "text", "required": False},
    {"key": "declarations_section", "label": "Oświadczenia", "type": "section"},
    {"key": "status_studenta", "label": "Status studenta?", "type": "radio", "options": ["TAK", "NIE"], "required": True},
    {"key": "emerytura_renta", "label": "Ustalone prawo do emerytury lub renty?", "type": "radio", "options": ["TAK", "NIE"], "required": True},
    {"key": "niepelnosprawnosc", "label": "Ustalony stopień niepełnosprawności? (jeśli tak, podaj jaki)", "type": "text", "required": False},
    {"key": "education_section", "label": "Dotychczasowe wykształcenie", "type": "section"},
    {"key": "wyksztalcenie", "label": "Wykształcenie (nazwa szkoły, okres nauki)", "type": "textarea", "required": False},
    {"key": "employment_section", "label": "Przebieg dotychczasowego zatrudnienia", "type": "section"},
    {"key": "zatrudnienie", "label": "Przebieg zatrudnienia (zakład pracy, okres)", "type": "textarea", "required": False},
    {"key": "emergency_section", "label": "Kontakt w nagłych przypadkach", "type": "section"},
    {"key": "osoba_kontaktowa", "label": "Osoba do zawiadomienia w razie wypadku (imię i nazwisko, adres, telefon)", "type": "textarea", "required": False},
]

ZLECENIOBIORCA_FIELDS = [
    {"key": "imie_nazwisko", "label": "Imię (imiona) i nazwisko", "type": "text", "required": True},
    {"key": "pesel_paszport", "label": "Numer ewidencyjny PESEL lub Paszport", "type": "text", "required": True},
    {"key": "plec", "label": "Płeć", "type": "radio", "options": ["Kobieta", "Mężczyzna"], "required": True},
    {"key": "miejsce_data_urodzenia", "label": "Miejsce i data urodzenia", "type": "text", "required": True},
    {"key": "obywatelstwo_5", "label": "Obywatelstwo", "type": "text", "required": True},
    {"key": "work_permit_section", "label": "Dane potwierdzające zezwolenie na pracę", "type": "section"},
    {"key": "paszport_od", "label": "Paszport ważny od", "type": "date", "required": False},
    {"key": "paszport_do", "label": "Paszport ważny do", "type": "date", "required": False},
    {"key": "zezwolenie_od", "label": "Zezwolenie na pracę ważne od", "type": "date", "required": False},
    {"key": "zezwolenie_do", "label": "Zezwolenie na pracę ważne do", "type": "date", "required": False},
    {"key": "wiza_od", "label": "Wiza ważna od", "type": "date", "required": False},
    {"key": "wiza_do", "label": "Wiza ważna do", "type": "date", "required": False},
    {"key": "telefon_7", "label": "Numer telefonu wraz z numerem kierunkowym", "type": "text", "required": True},
    {"key": "address_section", "label": "Adres zamieszkania w Polsce", "type": "section"},
    {"key": "wojewodztwo", "label": "Województwo", "type": "text", "required": False},
    {"key": "powiat", "label": "Powiat", "type": "text", "required": False},
    {"key": "gmina", "label": "Gmina", "type": "text", "required": False},
    {"key": "poczta", "label": "Poczta", "type": "text", "required": False},
    {"key": "ulica", "label": "Ulica nr domu/nr lokalu", "type": "text", "required": False},
    {"key": "kod_pocztowy", "label": "Kod pocztowy", "type": "text", "required": False},
    {"key": "miejscowosc", "label": "Miejscowość", "type": "text", "required": False},
    {"key": "urzad_skarbowy", "label": "Nazwa Urzędu Skarbowego", "type": "text", "required": False},
    {"key": "declarations_section", "label": "Oświadczenia (pkt 10)", "type": "section"},
    {"key": "zatrudnienie_inne", "label": "Jestem/nie jestem zatrudniony/a na podstawie umowy o pracę w innym zakładzie pracy (nazwa zakładu, dochód wyższy/niższy niż minimalne wynagrodzenie)", "type": "textarea", "required": False},
    {"key": "dzialalnosc_gospodarcza", "label": "Prowadzę/nie prowadzę działalność gospodarczą; opłacam składki na ubezpieczenie społeczne", "type": "radio", "options": ["Prowadzę, TAK", "Prowadzę, NIE", "Nie prowadzę"], "required": True},
    {"key": "emerytura_renta", "label": "Jestem/nie jestem uprawniony do emerytury/renty", "type": "radio", "options": ["Jestem uprawniony/a", "Nie jestem uprawniony/a"], "required": True},
    {"key": "niepelnosprawnosc", "label": "Posiadam/nie posiadam orzeczony stopień niezdolności do pracy (jeśli tak, podaj jaki)", "type": "text", "required": False},
    {"key": "status_studenta", "label": "Jestem/nie jestem uczniem/studentem", "type": "radio", "options": ["Jestem", "Nie jestem"], "required": True},
    {"key": "dobrowolne_ubezpieczenie", "label": "Wnoszę/nie wnoszę o objęcie dobrowolnym ubezpieczeniem chorobowym", "type": "radio", "options": ["Wnoszę", "Nie wnoszę"], "required": True},
    {"key": "emergency_section", "label": "Kontakt w nagłych przypadkach", "type": "section"},
    {"key": "osoba_kontaktowa", "label": "Osoba do zawiadomienia w razie wypadku (imię i nazwisko, adres, telefon)", "type": "textarea", "required": False},
    {"key": "payment_section", "label": "Sposób wypłaty wynagrodzenia", "type": "section"},
    {"key": "wyplata_sposob", "label": "Sposób wypłaty", "type": "radio", "options": ["Do rąk własnych", "Na konto bankowe"], "required": True},
    {"key": "nazwa_banku", "label": "Nazwa i adres banku", "type": "text", "required": False},
    {"key": "numer_konta", "label": "Pełny numer konta bankowego", "type": "text", "required": False},
]
