# Generated by Django 6.0.5 on 2026-05-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data od')),
                ('end_date', models.DateField(verbose_name='Data do')),
                ('days_count', models.IntegerField(verbose_name='Liczba dni roboczych')),
                ('reason', models.TextField(blank=True, verbose_name='Powód')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na akceptację'), ('approved', 'Zaakceptowany'), ('rejected', 'Odrzucony'), ('cancelled', 'Anulowany')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vacations', to=settings.AUTH_USER_MODEL, verbose_name='Akceptujący')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_vacations', to=settings.AUTH_USER_MODEL, verbose_name='Anulowany przez')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Wniosek złożony przez')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Wniosek urlopowy',
                'verbose_name_plural': 'Wnioski urlopowe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacationBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Rok')),
                ('allocated_days', models.IntegerField(default=0, verbose_name='Przyznane dni urlopu')),
                ('carried_over', models.IntegerField(default=0, verbose_name='Przeniesione z poprzedniego roku')),
                ('used_days', models.IntegerField(default=0, verbose_name='Wykorzystane dni urlopu')),
                ('remote_days_allocated', models.IntegerField(default=0, verbose_name='Przyznane dni zdalnych')),
                ('remote_days_used', models.IntegerField(default=0, verbose_name='Wykorzystane dni zdalnych')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Bilans urlopowy',
                'verbose_name_plural': 'Bilanse urlopowe',
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
