# Generated by Django 6.0.5 on 2026-05-19 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_vacationtype_alloc_conflict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa kalendarza')),
                ('year', models.IntegerField(verbose_name='Rok')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kalendarz pracowniczy',
                'verbose_name_plural': 'Kalendarze pracownicze',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SingleHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('date', models.DateField(verbose_name='Data')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_holidays', to='hr.workcalendar')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('calendar', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RecurringHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('month', models.IntegerField(verbose_name='Miesiąc')),
                ('day', models.IntegerField(verbose_name='Dzień')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_holidays', to='hr.workcalendar')),
            ],
            options={
                'ordering': ['month', 'day'],
                'unique_together': {('calendar', 'month', 'day')},
            },
        ),
        migrations.CreateModel(
            name='CalendarAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_assignments', to=settings.AUTH_USER_MODEL)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.workcalendar')),
            ],
            options={
                'verbose_name': 'Przypisanie kalendarza',
                'verbose_name_plural': 'Przypisania kalendarzy',
                'unique_together': {('employee', 'calendar')},
            },
        ),
    ]
