# Generated by Django 6.0.5 on 2026-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_workcalendar_singleholiday_recurringholiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Zarchiwizowany'),
        ),
    ]
