# Generated by Django 6.0.5 on 2026-05-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Treść pytania')),
                ('question_type', models.CharField(choices=[('single', 'Jedna odpowiedź'), ('multiple', 'Wiele odpowiedzi')], default='single', max_length=20)),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Pytania',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Treść odpowiedzi')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Poprawna')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_module.question')),
            ],
            options={
                'verbose_name': 'Odpowiedź',
                'verbose_name_plural': 'Odpowiedzi',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tytuł testu')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('category', models.CharField(choices=[('BHP', 'BHP'), ('RODO', 'RODO'), ('custom', 'Inne')], max_length=20, verbose_name='Kategoria')),
                ('passing_score', models.IntegerField(default=70, verbose_name='Próg zaliczenia (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests_module.test'),
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Termin')),
                ('status', models.CharField(choices=[('pending', 'Do wykonania'), ('completed', 'Wykonany')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to=settings.AUTH_USER_MODEL, verbose_name='Przypisany przez')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tests_module.test')),
            ],
            options={
                'verbose_name': 'Przypisanie testu',
                'verbose_name_plural': 'Przypisania testów',
                'ordering': ['-assigned_at'],
                'unique_together': {('test', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Wynik (%)')),
                ('passed', models.BooleanField(verbose_name='Zaliczony')),
                ('answers', models.JSONField(verbose_name='Odpowiedzi')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests_module.testassignment')),
            ],
            options={
                'verbose_name': 'Podejście do testu',
                'verbose_name_plural': 'Podejścia do testów',
                'ordering': ['-completed_at'],
            },
        ),
    ]
