# Generated by Django 6.0.5 on 2026-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_module', '0002_test_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Szablon testu'),
        ),
    ]
