# Generated by Django 6.0.5 on 2026-05-14 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email odbiorcy')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Imię i nazwisko odbiorcy')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('completed', 'Wypełniony'), ('expired', 'Wygasły')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Wygasa')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Wysłany przez')),
            ],
            options={
                'verbose_name': 'Zaproszenie do kwestionariusza',
                'verbose_name_plural': 'Zaproszenia do kwestionariuszy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Dane formularza')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wypełnienia')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='questionnaire.questionnaireinvitation', verbose_name='Zaproszenie')),
            ],
            options={
                'verbose_name': 'Wypełniony kwestionariusz',
                'verbose_name_plural': 'Wypełnione kwestionariusze',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nazwa szablonu')),
                ('type', models.CharField(choices=[('pracownik', 'Kwestionariusz dla pracownika (UoP)'), ('zleceniobiorca_cudzoziemiec', 'Kwestionariusz dla zleceniobiorcy - cudzoziemca'), ('custom', 'Własny szablon')], max_length=50, verbose_name='Typ')),
                ('fields_schema', models.JSONField(default=list, verbose_name='Schemat pól')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
            ],
            options={
                'verbose_name': 'Szablon kwestionariusza',
                'verbose_name_plural': 'Szablony kwestionariuszy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='questionnaireinvitation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='questionnaire.questionnairetemplate', verbose_name='Szablon'),
        ),
    ]
