# Generated by Django 6.0.5 on 2026-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireinvitation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Usunięty'),
        ),
        migrations.AlterField(
            model_name='questionnaireinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('completed', 'Wypełniony'), ('expired', 'Wygasły'), ('cancelled', 'Anulowany')], default='pending', max_length=20),
        ),
    ]
