# Generated by Django 6.0.5 on 2026-05-21 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Zdjęcie')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Aktualność',
                'verbose_name_plural': 'Aktualności',
                'ordering': ['-created_at'],
            },
        ),
    ]
