# Generated by Django 6.0.5 on 2026-06-25 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_password_reset_token'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='news/attachments/'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newspost',
            name='visibility',
            field=models.CharField(choices=[('all', 'Wszyscy'), ('dept', 'Wybrane działy'), ('person', 'Wybrane osoby')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='newspost',
            name='visible_to_depts',
            field=models.ManyToManyField(blank=True, related_name='visible_posts', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, related_name='visible_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newspost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
